# Uncomment the next line to define a global platform for your project
 platform :ios, '13.2'
 use_frameworks!


target 'Relational' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for Relational

  target 'RelationalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RelationalUITests' do
    # Pods for testing
  end

# add the Firebase pod for Google Analytics
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Analytics'
pod 'KeyboardObserving'
pod 'FirebaseUI'
pod 'Firebase/Storage'
pod 'SDWebImageSwiftUI'


# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

end
